export const FETCH_API_REQUEST = 'FETCH_API_REQUEST';
export const FETCH_API_SUCESS = 'FETCH_API_SUCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
export const SET_REDIRECTFLAG  = 'SET_REDIRECTFLAG';